FROM ubuntu:latest

RUN apt update
RUN apt-get update && \
    apt-get upgrade -y
RUN apt-get install -y git
RUN apt-get install -y git python3-pip

RUN python3 -m pip install --user qmk

SHELL ["/bin/bash", "--login", "-c"]

RUN echo 'PATH="$HOME/.local/bin:$PATH"' >> $HOME/.bashrc && source $HOME/.bashrc